name: Build and Push Image to DockerHub
on:
  create:
    tags:
      - 'v*'
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare tags for image
        id: image-metadata
        run: echo "::set-output name=tag::${{ secrets.DOCKERHUB_USERNAME }}/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/v}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: true
          tags: ${{ steps.image-metadata.outputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./management
          push: true
          tags: ${{ steps.image-metadata.outputs.tag }}-management
