name: Build and Push Image to DockerHub
on:
  create:
    tags:
      - 'v*'
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare tags for image
        id: image-metadata
        run: |
          BASE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/v}"
          BASE_FROM_IMAGE="rabbitmq:${GITHUB_REF##*/v}"
          MANAGEMENT_POSTFIX='-management'
          echo "::set-output name=tag::${BASE_TAG}"
          echo "::set-output name=from-image::${BASE_FROM_IMAGE}"
          echo "::set-output name=tag-management::${BASE_TAG}${MANAGEMENT_POSTFIX}"
          echo "::set-output name=from-image-management::${BASE_FROM_IMAGE}${MANAGEMENT_POSTFIX}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.image-metadata.outputs.tag }}
          build-args: |
            FROM_IMAGE=${{ steps.image-metadata.outputs.from-image }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.image-metadata.outputs.tag-management }}
          build-args: |
            FROM_IMAGE=${{ steps.image-metadata.outputs.from-image-management }}
